name: Deploy Angular to S3

on:
  push:
    branches:
      - production  # branch 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  #version Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --configuration production

      - name: Deploy to S3
        run: |
          aws s3 sync dist/freelance_marketplace/ s3://freelancerfrontend --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
